In [4]:
import numpy as np
import pandas as pd

df = pd.DataFrame({'lovesPopcorn': [1,1,0,0,1,1,0], "lovesSoda": [1,0,1,1,1,0,0], "age": [7,12,18,35,38,50,83], "lovesCoolAsIce": [0,0,1,1,1,0,0]})

X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [5]:
# 1 - ∑(p²)
def gini(y):
	total = y.value_counts().sum()
	nYes = y.value_counts()[1]
	nNo = y.value_counts()[0]

	prob_true = (nYes/total)**2
	prob_false = (nNo/total)**2

	return 1 - np.sum(prob_true + prob_false)

def gini(y):
	return 1 - np.sum(y.value_counts(normalize=True) ** 2)

def weighted_gini(y_left, y_right):
	total = len(y_left) + len(y_right)
	gini_left = gini(y_left)
	gini_right = gini(y_right)
	return (len(y_left)/total) * gini_left + (len(y_right)/total) * gini_right

In [6]:
def best_split(X, y):
	best_gini = 1
	best_feature = None
	best_threshold = None
	for feature in X.columns:
		#feature = 'lovesSoda'
		values = X[feature].unique()
		
		for val in values:
			left_idx = X[feature] <= val #  Does not lovesPopcorn
			right_idx = ~left_idx		# 	lovesPopcorn

			#target variable
			y_left = y[left_idx] # Does not lovesPopcorn(0) and lovesCoolAsIce(0,1)
			y_right = y[right_idx] # lovesPopcorn(1) and lovesCoolAsIce(0,1)
			

			if len(y_left) == 0 or len(y_right) == 0:
				continue
			
			gini_score = weighted_gini(y_left, y_right)

			if gini_score < best_gini:
				best_feature = feature
				best_gini = gini_score
				best_threshold = val
			
			#print(feature, val, np.round(gini_score, 2), np.round(best_gini,2), best_feature, best_threshold)
	
	return best_feature, best_threshold, np.round(gini_score,2)
		

best_split(X, y)

('lovesSoda', np.int64(0), np.float64(0.43))

In [7]:
class Node:
	def __init__(self, feature=None, threshold=None, left=None, right=None, value=None):
		self.feature = feature
		self.threshold = threshold
		self.left = left
		self.right = right
		self.value = value
	
	def is_leaf(self):
		  return self.value is not None

In [8]:
# def build_tree(X, y):

# 	print(pd.concat([X, y], axis=1))

# 	if len(y.unique()) == 1: # if no impurity left: target [0, 0, 0] or [1, 1, 1] not [0, 1, 0]
# 		return Node(value=y.mode()[0])
	
# 	feature, threshold, gini = best_split(X, y)
# 	print(feature, threshold, gini)

# 	left_idx = X[feature] <= threshold	# (no)
# 	right_idx = ~left_idx 				# (yes)
	
# 	print(pd.concat([X[left_idx], y[left_idx]], axis=1))
# 	print()
# 	left_leaf = build_tree(X[left_idx], y[left_idx])
# 	print(pd.concat([X[right_idx], y[right_idx]], axis=1))
# 	print()
# 	right_leaf = build_tree(X[right_idx], y[right_idx])
# 	print(left_leaf, right_leaf)
# 	print()   
# 	return Node(feature=feature, threshold=threshold, left=left_leaf, right=right_leaf)



# root = build_tree(X, y)

In [15]:
def build_tree(X, y, depth=0, max_depth=5):
    # Stopping criteria
    if len(y.unique()) == 1 or depth == max_depth:
        return Node(value=y.mode()[0])  # most common class

    feat, thresh, gini = best_split(X, y)

    if feat is None:
        print("rahda, radah")

    left_idx = X[feat] <= thresh
    right_idx = ~left_idx

    left = build_tree(X[left_idx], y[left_idx], depth+1, max_depth)
    right = build_tree(X[right_idx], y[right_idx], depth+1, max_depth)
	
    return Node(feature=feat, threshold=thresh, left=left, right=right)
root = build_tree(X,y)

In [20]:
def preOrderTraversal(node):
    if node.value is not None:
        print(node.value)
        return
    print(node.feature, node.value)
    preOrderTraversal(node.left)
    preOrderTraversal(node.right)
preOrderTraversal(root)

lovesSoda None
0
age None
0
1

In [12]:
df[~(X['lovesSoda'] <= 0)]

   lovesPopcorn  lovesSoda  age  lovesCoolAsIce
0             1          1    7               0
2             0          1   18               1
3             0          1   35               1
4             1          1   38               1

In [13]:
df[X['lovesSoda'] <= 0]

   lovesPopcorn  lovesSoda  age  lovesCoolAsIce
1             1          0   12               0
5             1          0   50               0
6             0          0   83               0

In [14]:
def build_tree(X, y):
	
	feature, threshold = best_split(X, y)
	Node(feature)


build_tree(X,y)

ValueError: too many values to unpack (expected 2)

In [ ]:
def split(X, y, feature_index, threshold):
	# return: left_X, left_y, right_X, right_y

_IncompleteInputError: incomplete input (3850024955.py, line 2)