In [3]:
import pandas as pd

df = pd.read_csv("../data/digit-recognizer/train.csv")
df

       label  pixel0  pixel1  pixel2  ...  pixel780  pixel781  pixel782  pixel783
0          1       0       0       0  ...         0         0         0         0
1          0       0       0       0  ...         0         0         0         0
2          1       0       0       0  ...         0         0         0         0
3          4       0       0       0  ...         0         0         0         0
4          0       0       0       0  ...         0         0         0         0
...      ...     ...     ...     ...  ...       ...       ...       ...       ...
41995      0       0       0       0  ...         0         0         0         0
41996      1       0       0       0  ...         0         0         0         0
41997      7       0       0       0  ...         0         0         0         0
41998      6       0       0       0  ...         0         0         0         0
41999      9       0       0       0  ...         0         0         0         0

[42000 rows x 785 columns]

In [4]:
# import matplotlib.pyplot as plt

# plt.imshow(df.iloc[0, 1:].values.reshape(28,28))

In [5]:
from sklearn.model_selection import train_test_split

X = df.iloc[:, 1:]
y = df.iloc[:, 0]

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.2)

In [6]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [7]:

y_pred = knn.predict(X_test)

In [9]:
from sklearn.decomposition import PCA

pca = PCA(n_components=3)
X_train = pca.fit_transform(X_train)
X_test = pca.fit_transform(X_test)
pd.DataFrame(X_train)

                 0            1           2
0      -226.605235  -305.894371 -417.175638
1        38.335837   461.091520 -100.408407
2      -305.492255   351.671417  961.347579
3        82.854104 -1106.895014  212.732009
4      -686.383803  -649.675584  167.755661
...            ...          ...         ...
33595  -180.317929  -604.309897 -473.759704
33596   -72.844949  -562.617207  103.346159
33597   -28.001334  -596.062872 -606.251309
33598   233.970113   -18.647791  148.274818
33599  1096.503736   254.723332  560.333548

[33600 rows x 3 columns]